# Generated by Django 4.2.5 on 2023-09-21 10:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
        ('network_security', '0002_rename_subscription_id_networksecuritygroup_subscription_and_more'),
        ('subnet', '0001_initial'),
        ('public_ip', '0001_initial'),
        ('subscription', '0002_rename_user_profile_id_subscription_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('network_security_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_security.networksecuritygroup')),
                ('public_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_ip.publicip')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.storage')),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subnet.subnet')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.subscription')),
            ],
        ),
    ]
