# Generated by Django 4.2.5 on 2023-09-21 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='user_profile_id',
            new_name='user_profile',
        ),
    ]
