# Generated by Django 4.2.5 on 2023-09-21 04:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkSecurityGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('subscription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkSecurityPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('network_security_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_security.networksecuritygroup')),
            ],
        ),
    ]
