# Generated by Django 4.2.5 on 2023-09-21 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_security', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networksecuritygroup',
            old_name='subscription_id',
            new_name='subscription',
        ),
        migrations.RenameField(
            model_name='networksecuritypolicy',
            old_name='network_security_group_id',
            new_name='network_security_group',
        ),
    ]
